name: CI Pipeline

# Trigger the workflow on push or pull request events
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define the jobs for this workflow
jobs:
  build:

    # Define the environment (Ubuntu Linux)
    runs-on: ubuntu-latest

    # Steps within the job
    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Java JDK 17 (or whatever version you are using)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # (or 'zulu', 'adopt', etc.)
          java-version: '17'

      # Step 3: Cache Maven dependencies to speed up the build
      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Build and run tests using Maven
      - name: Build with Maven
        run: mvn clean install

      # Step 5: Run tests
      - name: Run Tests
        run: mvn test
